primary-solution = "full"
check-type = "builtin"
name = "a-plus-b"
title = "P == NP?" # Clickbait :)
seed = "TheVerySecretSeed"

[builtin-check]
name = "cmp-tokens"

[[tests]]
map = "1..3"
testgen = "main"

[[tests]]
map = "4..5"
files = "{:0>1}.txt"

[[tests]]
map = "6..20"
testgen = "random"