check-type = "custom"
name = "array-sum"
title = "Finding Maximal Flow in Highly Parallel Networks"
random-seed = "c4142a74815ae779"
valuer = "icpc"

[custom-check]
pass-correct = false

[[tests]]
map = "1..2"
files = "%d.txt"

[[tests]]
map = "3..20"
testgen = ["main"]
