name="cpp"
suffix="cpp"
[[build]]
argv=["g++", "$(System.SourceFilePath)", "-o", "$(System.BinaryFilePath)", "-std=c++17", "-Wall", "-Wextra", "-Wpedantic", "-DJJS"]
[run]
argv=["$(System.BinaryFilePath)"]