name="cpp"
filename="source.cpp"
[[build]]
argv=["/usr/bin/g++", "$(Submission.SourceFilePath)", "-o", "$(Submission.BinaryFilePath)", "-std=c++17", "-Wall"
, "-Wextra", "-Wpedantic", "-DONLINE_JUDGE"]
[run]
argv=["$(Submission.BinaryFilePath)"]
