name="cpp"
filename="source.cpp"
[[build]]
argv=["/usr/bin/g++", "$(System.SourceFilePath)", "-o", "$(System.BinaryFilePath)", "-std=c++17", "-Wall", "-Wextra", "-Wpedantic", "-DONLINE_JUDGE"]
[run]
argv=["$(System.BinaryFilePath)"]