name="cpp"
suffix="cpp"
[[build]]
argv=["/bin/busybox", "ls", "/"]
[[build]]
argv = ["/bin/busybox", "ls", "/jjs"]
[[build]]
argv=["/usr/bin/g++", "$(System.SourceFilePath)", "-o", "$(System.BinaryFilePath)", "-std=c++17", "-Wall", "-Wextra", "-Wpedantic", "-DJJS"]
[run]
argv=["$(System.BinaryFilePath)"]