[package]
name = "soft"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
structopt = "0.3.3"
serde_json = "1.0.41"
serde = {version = "1.0.101", features = ["derive"]}
anyhow = "1.0.12"
util = {path = "../util"}
toml = "0.5.3"
copy-ln = { git = "https://github.com/mikailbag/copy-ln", branch = "master" }
tempfile = "3.1.0"
