[package]
name = "jjs_http"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
#actix-web = "0.7.8"
frontend_api = {path = "../jjs/frontend_api"}
#listenfd = "0.3.3"
rocket = "0.3.17"
rocket_codegen = "0.3.17"
handlebars = "1.1.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
uuid = { version = "0.7.1", features = ["v4"] }
failure = "0.1.3"
multipart = "0.15.3"
thrift = "0.0.4"
base64 = "0.10.0"

[dependencies.rocket_contrib]
version = "0.3.17"
default-features = false
features = ["handlebars_templates"]
