[package]
name = "frontend"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
frontend_api = {path = "../frontend_api"}
serde_json = "1.0.36"
serde = "1.0.84"
failure = "0.1.5"
failure_derive = "0.1.5"
rand = "0.6.4"
db = {path = "../db"}
postgres = "0.15.2"
thrift = "0.12.0"
[dependencies.rocket_contrib]
version = "0.4.0"
features = ["json"]
[dependencies.db_conn]
path = "../db_conn"
