[package]
name = "frontend"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
frontend_api = {path = "../frontend_api"}
serde_json = "1.0.33"
serde = "1.0.80"
failure = "0.1.3"
failure_derive = "0.1.3"
rand = "0.6.0"
db = {path = "../db"}
postgres = "0.15.2"
thrift = "0.0.4"
[dependencies.rocket_contrib]
version = "0.3.17"
features = ["json"]
[dependencies.db_conn]
path = "../db_conn"
