cargo-features = ["default-run"]

[package]
name = "frontend"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"
default-run = "frontend"

[[bin]]
path = "./bin/submit.rs"
name = "submit"

[dependencies]
cfg = {path = "../cfg"}
frontend-api = {path = "../frontend-api"}
serde_json = "1.0.39"
serde = "1.0.89"
failure = "0.1.5"
failure_derive = "0.1.5"
rand = "0.6.5"
db = {path = "../db"}
diesel = { version = "1.4.1", features = ["postgres", "extras"] }
rocket = "0.4.0"
r2d2 = "0.8.3"
dotenv = "0.13.0"
serde_derive = "1.0.89"
rand_chacha = "0.1.1"
sha3 = "0.8.1"
digest = "0.8.0"
branca = "0.8.0"
base64 = "0.10.1"
structopt = "0.2.15"
reqwest = "0.9.11"


[dependencies.rocket_contrib]
version = "0.4.0"
features = ["json"]
