[package]
name = "frontend"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
rocket = "0.3.16"
rocket_codegen = "0.3.16"
frontend_api = {path = "../frontend_api"}
serde_json = "1.0.31"
serde = "1.0.79"
failure = "0.1.2"
failure_derive = "0.1.2"
rand = "0.5.5"
uuid = {version = "0.7.1", features = ["v4"]}
db = {path = "../db"}
postgres = "0.15.2"
