[package]
name = "frontend"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
cfg = {path = "../cfg"}
frontend-api = {path = "../frontend-api"}
serde_json = "1.0.38"
serde = "1.0.87"
failure = "0.1.5"
failure_derive = "0.1.5"
rand = "0.6.5"
db = {path = "../db"}
postgres = "0.15.2"
rocket = "0.4.0"
r2d2 = "0.8.3"
r2d2_postgres = "0.14.0"
dotenv = "0.13.0"
[dependencies.rocket_contrib]
version = "0.4.0"
features = ["json"]
[dependencies.db-conn]
path = "../db-conn"
