[package]
name = "frontend"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
rocket = "0.3.17"
rocket_codegen = "0.3.17"
frontend_api = {path = "../frontend_api"}
serde_json = "1.0.33"
serde = "1.0.80"
failure = "0.1.3"
failure_derive = "0.1.3"
rand = "0.6.0"
uuid = { version = "0.7.1", features = ["v4"] }
db = {path = "../db"}
postgres = "0.15.2"
thrift = "0.0.4"
thread_local = "0.3.6"
[dependencies.rocket_contrib]
version = "0.3.17"
features = ["json"]
