language: rust
cache:
  directories:
   - ~/.cargo
   - ~/.rustup
   - ~/build/MikailBag/jjs/target
dist: bionic
branches:
  only:
    - trying
    - staging
    - master

rust:
  - nightly-2019-09-28

env: CARGO_INCREMENTAL=0

before_install:
  - rm rust-toolchain
  - unset RUSTC_WRAPPER
  - rustup component add rustfmt clippy
  - bash src/deploy/deps.sh
  - wget -q -O - https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2-Linux-x86_64.sh > /tmp/cmake.sh
  - sudo bash /tmp/cmake.sh --skip-license --prefix=/usr
  - sudo rm -rf /usr/local/cmake-* # this is hack to make script use new cmake version
  - mkdir /tmp/sweep

script:
  - cargo jjs-check
  - cargo jjs-build
  - cargo jjs-test
  - if [ "$SECRET_ENABLED" = "1" ]; then
       cargo jjs-check --fail-fast --pvs --no-clippy --no-rustfmt --no-shellcheck --no-minion-ffi-c-example;
    fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: /opt/jjs/share/docs
  on:
    branch: master
