[workspace]
members=["db", "invoker", "execute", "config", "init-jjs-root", "frontend", "invoker-task", "frontend-api", "objects",
"minion-cli", "db-conn", "cleanup", "minion-ffi", "devtool", "webclient"]
