[workspace]
members=["db", "invoker", "execute", "cfg", "init-jjs-root", "frontend", "frontend-api", "domain",
"minion-cli", "db-conn", "cleanup", "minion-ffi", "devtool", "webclient", "disintegrate"]
