[package]
name = "invoker"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
minion = {path = "../minion"}
cfg = {path ="../cfg"}
serde = { version = "1.0.101", features = ["derive"] }
serde_derive = "1.0.101"
serde_json = "1.0.41"
db = {path = "../db"}
dotenv = "0.15.0"
slog = { version = "2.5.2", features = ["max_level_trace"] }
slog-term = "2.4.1"
slog-async = "2.3.0"
ctrlc = { version = "3.1.3", features = ["termination"] }
aho-corasick = "0.7.6"
invoker-api = {path = "../invoker-api"}
cfg-if = "0.1.10"
pom = {path = "../pom"}
libc = "0.2.65"
nix = "0.15.0"
snafu = "0.5.0"
memchr = "2.2.1"
strum = "0.16.0"
strum_macros = "0.16.0"
chrono = "0.4.9"
color-backtrace = { version = "0.2.3", optional = true }
tempfile = "3.1.0"
fs_extra = "1.1.0"
snafu-derive = "0.5.0"
atty = "0.2.13"
base64 = "0.10.1"
bitflags = "1.2.1"
util = {path = "../util"}
slog-scope = "4.2.0"

[features]
beautiful_backtrace = ["color-backtrace"]
default = ["beautiful_backtrace"]
