[package]
name = "all"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
frontend-engine = {path = "../frontend-engine"}

[dev-dependencies]
reqwest = "0.9.20"
serde_json = "1.0.40"
base64 = "0.10.1"
