title="C++"
filename="source.cpp"

[build-limits]
time = 6000

[[build]]
argv=["{{ env_GPP }}", "$(Run.SourceFilePath)", "-o", "$(Run.BinaryFilePath)", "-std=c++17", "-Wall"
, "-Wextra", "-Wpedantic", "-DONLINE_JUDGE"]

[run]
argv=["$(Run.BinaryFilePath)"]
