[package]
name = "invoker-api"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
strum = "0.16.0"
strum_macros = "0.16.0"
bitflags = "1.2.1"
pom = {path = "../pom"}