[package]
name = "db"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.3", features = ["postgres", "extras", "uuid", "uuidv07"] }
serde = { version = "1.0.101", features = ["derive"] }
uuid = { version = "0.7.4", features = ["serde", "v4"] }
snafu = "0.5.0"
snafu-derive = "0.5.0"
r2d2 = "0.8.6"
