[package]
name = "frontend_api"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
serde = "1.0.82"
serde_derive = "1.0.82"
ordered-float = "1.0.1"
thrift = "0.0.4"
try_from = "0.3.2"
