[package]
name = "db"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
postgres = "0.15.2"
diesel = { version = "1.4.2", features = ["postgres"] }
diesel_derives = "1.4.0"
diesel-derive-enum = { version = "0.4.4", features = ["postgres"] }
serde = "1.0.90"
serde_derive = "1.0.90"
