[[toolchains]]
name="cpp"
extension="cpp"
[[toolchains.build_commands]]
env= {}
argv=["g++", "$(System.SourceFilePath)", "-o", "$(System.BinaryFilePath)", "-std=c++17", "-Wall", "-Wextra", "-Wpedantic", "-DJJS"]
cwd="."
[toolchains.run_command]
env={}
cwd="."
argv=["$(System.BinaryFilePath)"]