[package]
name = "minion"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
libc= "0.2.54"
errno= "0.2.4"
rand = "0.6.5"
cfg-if = "0.1.7"
field-offset = "0.1.1"
serde = "1.0.91"
serde_json = "1.0.39"
serde_derive = "1.0.91"
failure = "0.1.5"
tiny-nix-ipc = { git = "https://github.com/mikailbag/tiny-nix-ipc", rev = "bfd29b8b05098c132dd30cd1c7909377e88cb789", features = ["ser_cbor"] }
procfs = "0.5.2"
nix = "0.13.0"
downcast-rs = "1.0.4"
