title = "JJS Demo contest"
vis-unreg = true
vis-anon = true
group = ["Users"]

[[problems]]
code = "A"
name = "a-plus-b"

[[problems]]
code = "B"
name = "array-sum"

[[problems]]
code = "C"
name = "sqrt"
