toolchain-root= "/opt/jjs-tc/root"
# TODO disable this option
env-passing = true
env-blacklist = ["LS_COLORS"]

[global-env]
PATH = "/usr/bin"
LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/8/"
