[package]
name = "execute"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
libc= "0.2.45"
errno= "0.2.4"
rand = "0.6.1"
cfg-if = "0.1.6"
field-offset = "0.1.1"
serde = "1.0.82"
serde_json = "1.0.33"
serde_derive = "1.0.82"
failure = "0.1.3"
