[package]
name = "execute"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
libc= "0.2.43"
errno= "0.2.4"
rand = "0.6.0"
cfg-if = "0.1.6"
field-offset = "0.1.1"
