[package]
name = "invoker"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
execute = {path = "../execute"}
config = {path ="../config"}
pretty_env_logger = "0.3.0"
futures = "0.1.25"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.36"
rocket = "0.4.0"
rocket_codegen = "0.4.0"
invoker_task = {path = "../invoker_task"}
frontend_api = {path = "../frontend_api"}
db = {path = "../db"}
db_conn = {path = "../db_conn"}

[dependencies.amqp]
version = "0.1.2"
default-features = false
features = []
