[package]
name = "invoker"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]

[dependencies]
execute = {path = "../execute"}
config = {path ="../config"}
pretty_env_logger = "0.2.4"
futures = "0.1.23"
serde = "1.0.75"
serde_derive = "1.0.75"
serde_json = "1.0.26"
rocket = "0.3.16"
rocket_codegen = "0.3.16"
invoker_task = {path = "../invoker_task"}
frontend_api = {path = "../frontend_api"}
capnp = "0.9.0"

[dependencies.amqp]
version = "0.1.1"
default-features = false
features = []
