[package]
name = "invoker"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
execute = {path = "../execute"}
config = {path ="../config"}
pretty_env_logger = "0.3.0"
futures = "0.1.25"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.36"
rocket = "0.4.0"
rocket_codegen = "0.4.0"
frontend-api = {path = "../frontend-api"}
db = {path = "../db"}
db-conn = {path = "../db-conn"}
dotenv = "0.13.0"
domain = {path = "../domain"}