[package]
name = "minion"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
libc= "0.2.66"
errno= "0.2.4"
rand = "0.7.2"
cfg-if = "0.1.10"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.44"
tiny-nix-ipc = { git = "https://github.com/myfreeweb/tiny-nix-ipc", features = ["ser_json", "zero_copy"] }
procfs = "0.7.5"
nix = "0.16.0"
downcast-rs = "1.1.1"
snafu = "0.6.0"
base64 = "0.11.0"
backtrace = "0.3.40"
