[package]
name = "deploy"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"


[[bin]]
name = "configure"
path = "bin/configure.rs"

[[bin]]
name = "make"
path = "bin/make.rs"

[dependencies]
structopt = "0.3.2"
console = "0.9.0"
serde_json = "1.0.41"
fs_extra = "1.1.0"
filetime = "0.2.7"
tar = "0.4.26"
serde = { version = "1.0.101", features = ["derive"] }
shell-escape = "0.1.4"
tera = "0.11.20"
