name: "deploy"
on:
  push:
    branches:
      - master
      - ci # TODO: temp, do not forget to remove in followup PR
env:
  CI: 1
  RUST_BACKTRACE: full
jobs:
  docker:
    name: docker
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: actions/checkout@v1
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2019-09-28
          override: true
      - name: install global dependencies
        run: bash scripts/ci-env.sh
      - name: cargo jjs-build
        run: cargo jjs-build
      - name: upload docker images
        run: |
          docker login --username mikailbag --password ${{ secrets.PKG_REGISTRY_TOKEN }} docker.pkg.github.com
          docker tag jjs-frontend:dev docker.pkg.github.com/mikailbag/jjs/frontend:master
          docker push docker.pkg.github.com/mikailbag/jjs/frontend:master
          docker tag jjs-invoker:dev docker.pkg.github.com/mikailbag/jjs/invoker:master
          docker push docker.pkg.github.com/mikailbag/jjs/invoker:master
          docker tag jjs-tools:dev docker.pkg.github.com/mikailbag/jjs/tools:master
          docker push docker.pkg.github.com/mikailbag/jjs/tools:master
