name: "deploy"
on:
  push:
    branches:
      - master
env:
  CI: 1
  RUST_BACKTRACE: full
jobs:
  docker:
    name: docker
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: actions/checkout@v1
      - name: install global dependencies
        run: bash scripts/ci-env.sh
      - name: cargo jjs-build
        run: cargo jjs-build
        env:
          JJS_DT_DEPLOY: docker
      - name: upload docker images
        run: |
          docker login --username mikailbag --password ${{ secrets.PKG_REGISTRY_TOKEN }} docker.pkg.github.com
          docker tag jjs-frontend:latest docker.pkg.github.com/mikailbag/jjs/frontend:master
          docker push docker.pkg.github.com/mikailbag/jjs/frontend:master
          docker tag jjs-invoker:latest docker.pkg.github.com/mikailbag/jjs/invoker:master
          docker push docker.pkg.github.com/mikailbag/jjs/invoker:master
          docker tag jjs-tools:latest docker.pkg.github.com/mikailbag/jjs/tools:master
          docker push docker.pkg.github.com/mikailbag/jjs/tools:master
  deb:
    name: deb
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: actions/checkout@v1
      - name: Setup env
        run: bash scripts/ci-env.sh
      - name: Build debian package
        run: cargo jjs-build --deb
        env:
          JJS_DT_DEPLOY: deb
      - name: Publish debian package artifact
        uses: actions/upload-artifact@v1
        with:
          name: jjs-amd64.deb
          path: /opt/jjs/pkg/jjs.deb
  man:
    name: man
    if: false # TODO
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: actions/checkout@v1
      - name: install global dependencies
        run: |
          bash scripts/ci-env.sh
          cargo install mdbook -Z install-upgrade
      - name: cargo jjs-build
        run: cargo jjs-build
        env:
          JJS_DT_DEPLOY: man
      - name: upload man
        run: |
          echo TODO
