name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@master
      - name: Prepare environment
        run: |
          rustup default nightly-2019-08-01
          rustup component add clippy rustfmt
          sudo apt update
          sudo apt install -y libpq-dev
          sudo apt upgrade -y shellcheck
      - name: Check formatting and lint with clippy
        run: cargo build-jjs
      - name: Run tests
        run: cargo test-jjs
