name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check formatting and lint with clippy 
      uses: docker://mikailbag/jjs-dev:gh-70feb585b6ab9b738c3abe984e83cb81588e89f5
      runs: cargo build-jjs
      
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      uses: docker://mikailbag/jjs-dev:gh-70feb585b6ab9b738c3abe984e83cb81588e89f5
      runs: cargo test-jjs
      
  docs:
      runs-on: ubuntu-latest
      needs: [build]
      steps:
      - name: Generate documentation
        uses: docker://mikailbag/jjs-dev:gh-70feb585b6ab9b738c3abe984e83cb81588e89f5
        runs: cargo docs-jjs
