name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        run: rustup default nightly-2019-08-01
      - name: Check formatting and lint with clippy
        run: cargo build-jjs
      - name: Run tests
        run: cargo test-jjs
      - name: Generate documentation
        run: cargo docs-jjs