name: "ci"
on:
  pull_request: {}
  push:
    branches:
      - staging
      - trying
env:
  CI: 1
  RUST_BACKTRACE: full
jobs:
  check:
    name: check
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: actions/checkout@v1
      - name: install global dependencies
        run: bash scripts/ci-env.sh
        env:
          SECRET_ENABLED: ${{ secrets.SECRET_ENABLED }}
          PVS_NAME: ${{ secrets.PVS_NAME }}
          PVS_LICENSE_KEY: ${{ secrets.PVS_LICENSE_KEY }}
      - name: cargo jjs-check
        run: cargo jjs-check
        env:
          SECRET_ENABLED: ${{ secrets.SECRET_ENABLED }}

  unit-tests:
    name: unit-tests
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: actions/checkout@v1
      - name: install global dependencies
        run: bash scripts/ci-env.sh
      - name: cargo jjs-test
        run: cargo jjs-test

  build:
    name: build
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: actions/checkout@v1
      - name: install global dependencies
        run: bash scripts/ci-env.sh
      - name: cargo jjs-build
        run: cargo jjs-build
  udeps:
    name: udeps
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: actions/checkout@v1
      - name: install global dependencies
        run: |
          bash scripts/ci-env.sh
          cargo install cargo-udeps
      - name: cargo-udeps
        run: cargo jjs-check --no-default --udeps

  e2e:
    name: e2e
    runs-on: 'ubuntu-18.04'
    needs: build
    if: false # TODO
    steps:
      - uses: actions/checkout@v1
      - name: download jjs artifacts
        uses: actions/download-artifact@v1
        with:
          name: dist.tgz
          path: /opt/jjs
      - name: launch jjs
        run: docker-compose up --detach
      - name: run tests
        run: cargo jjs-test --integration-tests --skip-unit
      - name: collect logs
        if: always()
        run: docker-compose logs > logs.txt
      - name: upload logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: docker-compose-logs.txt
          path: ./logs.txt
